vich_uploader:
    db_driver: orm

    mappings:
        stock:
            uri_prefix: /stock
            upload_destination: '%kernel.project_dir%/public/stock'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
